version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/athena?serverTimezone=UTC
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JDBC_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - ATHENA_SPRING_ALIOSS_ENABLED=false
      - ATHENA_TEST_ENABLED=true
      - athena__alioss_endpoint_key=test_key
      - athena__table_name=TEST_META_DATA
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "mysql:8.0.26"
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_INIT_SCRIPT_PATH:-./mysql-init.sql}:/docker-entrypoint-initdb.d/mysql-init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    healthcheck:
      test: mysqladmin ping -h localhost -u root -proot
      timeout: 3s
      retries: 3
